COMMIT;

SHOW DATABASES;

CREATE DATABASE IF NOT EXISTS testdb4;

USE testdb4;

CREATE TABLE CUSTOMERS (
   ID INT NOT NULL,
   NAME VARCHAR (20) NOT NULL,
   AGE INT NOT NULL,
   ADDRESS CHAR (25),
   SALARY DECIMAL (18, 2),
   PRIMARY KEY (ID)
);

SHOW TABLES;

INSERT INTO CUSTOMERS VALUES 
(1, 'Ramesh', 32, 'Ahmedabad', 2000.00),
(2, 'Khilan', 25, 'Delhi', 1500.00),
(3, 'Kaushik', 23, 'Kota', 2000.00),
(4, 'Chaitali', 25, 'Mumbai', 6500.00),
(5, 'Hardik', 27, 'Bhopal', 8500.00),
(6, 'Komal', 22, 'Hyderabad', 4500.00),
(7, 'Muffy', 24, 'Indore', 10000.00);

SELECT * FROM customers;

START TRANSACTION;

UPDATE CUSTOMERS SET SALARY = SALARY + 500 WHERE ID = 1;
UPDATE CUSTOMERS SET SALARY = SALARY + 1000 WHERE ID = 2;
UPDATE CUSTOMERS SET SALARY = SALARY + 500 WHERE ID = 3;

COMMIT;

START TRANSACTION;

DELETE FROM customers WHERE id = 7;

COMMIT;

SELECT * FROM customers;

START TRANSACTION;

UPDATE CUSTOMERS SET SALARY = SALARY + 1000 WHERE ID = 6;

SELECT * FROM customers;

ROLLBACK;

SELECT * FROM customers;

COMMIT;

SAVEPOINT savepoint1;

SELECT * FROM customers;

START TRANSACTION;

UPDATE CUSTOMERS SET SALARY = SALARY + 2000 WHERE ID = 6;

SELECT * FROM customers;

ROLLBACK;

COMMIT;

SAVEPOINT SP1;